### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by majordookie** [atom-community/autocomplete-paths#42] opened 2015-02-04 01:23 UTC
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (C:\Users\Felipe\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:64:11)
Object.activate (C:\Users\Felipe\.atom\packages\autocomplete-paths\lib\autocomplete-paths.coffee:8:25)
```

**Comment by joefitzgerald** [comment] 2015-02-04 02:39
Please check the repo before opening issues. Duplicate of #41.

**Closed by joefitzgerald** 2015-02-04 02:39 UTC
