### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by rssawhney** [atom-community/autocomplete-paths#114] opened 2017-08-11 15:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.0.1

### Stack Trace

Uncaught Error: Unable to watch path

```
At /home/papajohn/.atom/packages/autocomplete-paths/node_modules/pathwatcher/lib/main.js:87

Error: Unable to watch path
    at HandleWatcher.start (/packages/autocomplete-paths/node_modules/pathwatcher/lib/main.js:87:29)
    at /packages/autocomplete-paths/node_modules/pathwatcher/lib/main.js:20:12)
    at /packages/autocomplete-paths/node_modules/pathwatcher/lib/main.js:140:30)
    at Object.exports.watch (/packages/autocomplete-paths/node_modules/pathwatcher/lib/main.js:234:12)
    at PathsCache._watchDirectory (/packages/autocomplete-paths/lib/paths-cache.js:57:33)
    at /packages/autocomplete-paths/lib/paths-cache.js:109:32
    at Array.forEach (native)
    at /packages/autocomplete-paths/lib/paths-cache.js:109:12
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:292:9
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:260:17
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:252:11
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:199:38
    at /usr/share/atom/resources/app/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:40.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-dracula-black 0.3.0 
atom-save-all 0.4.1 
atom-ternjs 0.18.3 
autocomplete-paths 2.0.1 
busy-signal 1.4.3 
color-picker 2.2.5 
Darkula-Web-syntax 0.5.0 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
file-icons 2.1.10 
flow-ide 1.8.1 
git-plus 7.9.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
linter 2.2.0 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-rubocop 2.1.1 
linter-ui-default 1.6.4 
pigments 0.40.2 
project-manager 3.3.5 
sync-settings 0.8.2 
terminal-fusion 2.4.4 
```

**Comment by saschagehlich** [comment] 2017-08-11 15:47
What are the steps to reproduce this? How large is your project?

**Comment by rssawhney** [comment] 2017-08-11 16:22
the error is thrown at the launch of atom only

the project is pretty big around 1000 plus files

**Comment by saschagehlich** [comment] 2017-08-11 16:25
Please check node-pathwatcher's troubleshooting guide: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#troubleshooting

**Comment by rssawhney** [comment] 2017-08-11 17:09
set the value higher than 32768, but still not working

**Comment by saschagehlich** [comment] 2017-08-11 17:10
I'll start working on a different approach now which will not do any additional watching (since atom already does this for us)

**Comment by saschagehlich** [comment] 2017-08-11 18:38
@rssawhney Could you try again with v2.1.0?

**Comment by saschagehlich** [comment] 2017-08-12 06:36
Closing this for now. Please re-open if issue persists.

**Closed by saschagehlich** 2017-08-12 06:36 UTC
