### ISSUE TITLE
Allow use autosuggestion in any file and scope

### ISSUE THREAD

**Issue by Alexance** [atom-community/autocomplete-paths#144] opened 2017-08-24 14:14 UTC
I propose to add functionality for autosuggestion for any file and scope of project. So, no need to define scope - user can manually activate autosuggestion by hotkey (like fuzzy matching after Ctrl/Cmd-Space).

I think it useful in cases when user wants to include/import file in custom place and out of predefined scopes.

**Comment by saschagehlich** [comment] 2017-08-24 14:17
This is a duplicate of #139 so I'm closing this

**Closed by saschagehlich** 2017-08-24 14:17 UTC
