### ISSUE TITLE
autocomplete doesn't works in *.vue

### ISSUE THREAD

**Issue by AlexQuidditch** [atom-community/autocomplete-paths#128] opened 2017-08-13 12:14 UTC
autocomplete doesn't works in *.vue files

**Comment by saschagehlich** [comment] 2017-08-13 12:30
Since I'm not a vue developer, I'm not sure what the expected behavior is. PR is very welcome though.

**Comment by giolf** [comment] 2017-08-19 21:50
I've the same issue:
in .js file everything works like a charm.  
But in .vue file nothing is working.

I think it's only necessary add a new scope and then it will work.
@saschagehlich  in a .vue file there is a <script></script> tag where you can add JS code. 
so it has to works like now in .js files. The only difference is he has to trigger in .vue files and show .vue results

**Comment by giolf** [comment] 2017-08-20 13:37
Ok fixed,
Add this scope in your `config.cson`:
```
"autocomplete-paths":
      scopes: [
          {
              scopes: ['text.html.vue'],
              prefixes: [
                  'import\\s+.*?from\\s+[\'"]',
                  'require\\([\'"]'
              ],
              extensions: ['js', 'vue'],
              relative: true,
              includeCurrentDirectory: true,
              replaceOnInsert: [
                  ['.jsx?$', '']
              ]
          }
      ]
```

**Comment by Alexance** [comment] 2017-08-23 15:42
#142

**Comment by saschagehlich** [comment] 2017-08-24 12:43
Thanks @Alexance and all the others for cooperating - landed in 2.8.1

**Closed by saschagehlich** 2017-08-24 12:43 UTC
Labels: enhancement

**Comment by AlexQuidditch** [comment] 2017-08-24 17:46
It's awesome, thanks! :)

**Comment by rainjm** [comment] 2017-09-07 09:41
![image](https://user-images.githubusercontent.com/9592236/30156934-8d07e98e-93f3-11e7-9012-d388c4ee2cf1.png)

SCSS @import doesn't works.

**Comment by dasisyouyu** [comment] 2018-04-11 15:21
@rainjm 
Please refer to this
autocomplete-paths/lib/config/default-scopes.js

In order to correspond to "@import" in the .vue format, it is probably necessary to add config.cson.

Please refer to the following for Additional notation method :)
https://github.com/atom-community/autocomplete-paths#defining-scopes
