### ISSUE TITLE
Maximum file count of 2000 has been exceeded. Path autocompletion will not work in this project.

### ISSUE THREAD

**Issue by ghost** [atom-community/autocomplete-paths#164] opened 2017-09-20 09:30 UTC
[maximum-file-limit-exceeded](https://github.com/atom-community/autocomplete-paths/wiki/Troubleshooting#maximum-file-limit-exceeded)

above document cannot solve this issues;

1、less 2000 file in my project
2、there is  a `.gitignore` file in my project
3、`node_modules` is in `.gitignore` file

i try deleted `node_modules` folder and this  issue will be solve

i am trouble with `Your project is not git-backed` in `maximum-file-limit-exceeded` wiki?

**Comment by saschagehlich** [comment] 2017-09-20 09:31
Is your project a git project? So, did you do `git init`? Otherwise the .gitignore will not be used. Is the `node_modules` folder greyed out in your project view?

**Comment by stratmm** [comment] 2017-09-20 10:18
I have been getting the same issue for several weeks, My project is git backed, `node_modules` is properly ignored and clearing `node_modules` fixes the issue.

**Comment by saschagehlich** [comment] 2017-09-20 10:24
@stratmm Does hit happen instantly (after opening the project) or just after some time?

**Comment by stratmm** [comment] 2017-09-20 10:32
@saschagehlich It happens a couple of seconds after opening the project, or a couple of seconds after executing a `Rebuild Cache`

**Comment by stratmm** [comment] 2017-09-20 10:34
@saschagehlich I suspect it might be due to one of the modules brought via npm, here is my dependency list.

```
  "dependencies": {
    "aws-sdk": "^2.4.12",
    "babel-runtime": "^6.23.0",
    "babelify": "^7.3.0",
    "event-stream": "^3.3.4",
    "highland": "^2.10.4",
    "js-base64": "^2.1.9",
    "lodash": "^4.17.4",
    "moment": "^2.17.1",
    "object-hash": "^1.1.8",
    "objectmodel": "^2.6.2",
    "restler": "^3.4.0",
    "string": "^3.3.3",
    "underscore": "^1.8.3",
    "uuid": "^3.0.1",
    "when": "^3.7.7"
  },
  "devDependencies": {
    "aws-sdk-mock": "^1.6.1",
    "babel-core": "^6.21.0",
    "babel-eslint": "^7.1.0",
    "babel-preset-node6": "^11.0.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "eslint": "^3.0.1",
    "eslint-config-standard": "^6.0.0",
    "eslint-plugin-babel": "^3.2.0",
    "eslint-plugin-promise": "^3.0.0",
    "eslint-plugin-standard": "^2.0.0",
    "mocha": "^3.2.0",
    "npm": "^2.2.0",
    "serverless-plugin-optimize": "^3.0.1-rc.1"
  },
```

**Comment by andy1028** [comment] 2017-09-21 04:29
i solved by uninstall all of atom plugins and atom itself

**Comment by FelipeSP** [comment] 2017-09-22 19:43
I experienced the same issue as @stratmm. Are **all** of your projects git-backed? Are **all** of your project node_modules greyed out? I sequentially removed the other project folders until it worked.

**Comment by saschagehlich** [comment] 2017-09-22 20:35
@stratmm @FelipeSP @andy1028 Are you using `project-viewer`?

**Comment by FelipeSP** [comment] 2017-09-22 20:48
No, I don't.

**Comment by mikestopcontinues** [comment] 2017-09-24 11:47
Same problem. Been happening for a month or so. It happens as soon as I open a project, even with `.gitignore`, `node_modules` is getting indexed.

**Comment by malimichael** [comment] 2017-09-25 19:17
Having same issue here. I get the error every time I open a project even if it is git backed and `node_modules` is in my `.gitignore`

**Comment by amandeepmittal** [comment] 2017-09-29 12:21
I am having the same problem with git initialised project directory that contains `.gitignore` file.

**Comment by stevehanson** [comment] 2017-09-29 14:51
I was having this problem and I seem to have resolved it by checking "Exclude VCS Ignored Paths" on the Atom Settings -> Core page.

![image](https://user-images.githubusercontent.com/1691324/31021332-1ff6c964-a4fb-11e7-9b0a-b4b791fa12ba.png)

It seems like maybe this package isn't respecting the globs set in "Ignored Names" in the settings and is maybe instead relying only on the "Exclude VCS Ignored Paths" setting? Is that so?

![image](https://user-images.githubusercontent.com/1691324/31021460-80eae53e-a4fb-11e7-8a9a-2aa1eda090ba.png)

**Comment by malimichael** [comment] 2017-09-29 16:24
I can confirm that checking the "Exclude VCS Ignored Paths" box fixed the issue for me. It may be helpful to add that step into the [troubleshooting](https://github.com/atom-community/autocomplete-paths/wiki/Troubleshooting#maximum-file-limit-exceeded)

**Comment by mikestopcontinues** [comment] 2017-09-29 22:08
That setting was already checked for me and I re-enabled it without fixing
the problem.

**Comment by saschagehlich** [comment] 2017-09-29 22:13
@mikestopcontinues @malimichael @malimichael @amandeepmittal @FelipeSP @stratmm Which OS are you using?

**Comment by Ahad-Wasim** [comment] 2017-09-30 10:29
Hmmm...I have the "Exclude VCS Ignored Paths" box checked on my end but the issue still persists. I tried adding node_modules into the Ignored Names list but I am still getting the maximum file count error.

**Comment by malimichael** [comment] 2017-10-01 10:21
@Ahad-Wasim MacOS Sierra 10.12.6

**Comment by malimichael** [comment] 2017-10-01 10:22
@saschagehlich macOS Sierra 10.12.6

**Comment by saschagehlich** [comment] 2017-10-01 15:51
@malimichael  Thanks!
@Ahad-Wasim Which OS are you on?

**Comment by mikestopcontinues** [comment] 2017-10-01 21:27
macOS Sierra 10.12.6

**Comment by stratmm** [comment] 2017-10-02 14:25
@saschagehlich I am on MAC OSX 10.12.6

**Comment by Ahad-Wasim** [comment] 2017-10-03 17:52
@saschagehlich - I am on macOS Sierea (10.12.6)

**Comment by FelipeSP** [comment] 2017-10-04 18:06
@saschagehlich Same here: macOS Sierra 10.12.6

**Comment by saschagehlich** [comment] 2017-10-09 06:17
Please try again with the latest version of autocomplete-paths

**Comment by stratmm** [comment] 2017-10-09 09:19
@saschagehlich Just tried with the latest version and got the same issue.  I have solved the problem in the sort-term by using `Exclude VCS Ignored Paths` and setting the `Ignored Names` but this is not ideal for me as I like quick access to ignored files especially for hunting through `node_modules/` code.

![screen shot 2017-10-09 at 10 14 41](https://user-images.githubusercontent.com/1633758/31331674-3816f59a-acdb-11e7-9939-163d38f8440a.png)

**Comment by StepanPanek** [comment] 2017-10-13 23:12
Hello, guys ! 

I had a same problem, which I have already solved.

As first open the instaled packages -> Find out "autocomplete-paths" package and open it's settings (https://imgur.com/a/lSKcK) -> When the settings are opened, scroll down and find out a label called "Max Fail Count" and change the number from 2.000 e.g. to 10.000. Restart Atom and it should be done.

It solved my problem. Wish you good luck!

**Comment by mikestopcontinues** [comment] 2017-10-14 01:06
That's not a solution, @StepanPanek. It's just a bandaid. If you have more
than 10k files in node_modules (a really easy task), then you'll get the
error. Not to mention that your memory usage will skyrocket AND your
autocomplete will get muddied up with a bunch of useless files.


Mike Stop Continues
*Website <https://mikestopcontinues.com/> · Facebook
<https://www.facebook.com/stopcontinues>
<https://mail.google.com/> · Twitter <https://twitter.com/stopcontinues>*
*Want free books? Join my list <http://mikestop.com/starter>.*

**Comment by katbow** [comment] 2017-10-17 10:46
I have the same thing happening even with the newest version. Went through the [trouble shooting guide](https://github.com/atom-community/autocomplete-paths/wiki/Troubleshooting#maximum-file-limit-exceeded) and nothing there applies for me.

**Comment by stevgouws** [comment] 2017-10-25 13:05
Same problem. It happens as soon as I uncheck `Exclude VCS Ignored Paths`.  I'm on OSx El Capitan 10.11.4. It's _not_ happening to a colleague of mine who's on Ubuntu 17.04, not sure if that could have anything to do with it?

**Comment by axe-z** [comment] 2017-11-06 16:41
same error here , VCS ignored path is checked... 10.12.6

**Comment by phphe** [comment] 2017-12-24 01:37
Hello. I was troubled by this issue. I pulled a request, it will solve it. https://github.com/atom-community/autocomplete-paths/pull/195

**Comment by phphe** [comment] 2017-12-25 05:03
I puslished a fork, use it brefore request merged. https://atom.io/packages/autocomplete-paths-ignore-circle-symlinks

**Comment by fruity4pie** [comment] 2018-03-01 17:09
Just add the dir "node_modules" into "Preferences -> Core -> Ignored Names" and relax :)

**Comment by stevgouws** [comment] 2018-03-02 04:33
It still happens though. Unless I ignore the vendor directory too, but that doesn't really help because then I need to go and change it every time I want to search for a PHP class.

**Comment by Lwenli1224** [comment] 2018-03-20 16:38
How to solve the problem that would have liked atom because the file path prompts don't want to use atom， solve！！！

**Comment by stevematdavies** [comment] 2019-07-01 08:19
Still having the very same problem in 2019, any solutions that work / fixes / patches?

**Comment by tojokely** [comment] 2019-08-30 01:08
@stevematdavies and for anyone still having this issue. If you use Atom, go to your config.cson file [settings -> open config folder on the left tab] and add _node_modules_ to the ignoredNames like the following: 

![auto complete paths](https://user-images.githubusercontent.com/16598216/63986267-4164f380-cae4-11e9-8dd4-ab858ed2f2f1.JPG)

**Comment by AlephQuiroz** [comment] 2020-01-16 09:58
> @stevematdavies y para cualquiera que todavía tenga este problema. Vaya a su archivo config.cson [configuración -> abra la carpeta de configuración en la pestaña izquierda] y agregue _node_modules_ a los nombres ignorados de la siguiente manera:
> 
> ![rutas de autocompletar](https://user-images.githubusercontent.com/16598216/63986267-4164f380-cae4-11e9-8dd4-ab858ed2f2f1.JPG)
> 
> También puede agregar cualquier otro nombre que desee que se ignore.

La verdad es que no me funciono  .

**Comment by afacadcam** [comment] 2020-03-23 03:39
![autocomplete](https://user-images.githubusercontent.com/51977433/77278629-6fb15700-6cf2-11ea-9596-ce498fea508f.png)

 Just add your count to higher, ex : 2000 -> 20000

**Closed** 2021-03-04 16:49 UTC
