### ISSUE TITLE
Memory leak in PathsCache

### ISSUE THREAD

**Issue by lierdakil** [atom-community/autocomplete-paths#143] opened 2017-08-24 12:16 UTC
I noticed `_filePathsByDirectory` is a bit of a memory hog after a while. For example, here's a part of heap snapshot:

name | depth | shallow size | % | retained size | %
-|-|-|-|-|-
_filePathsByDirectory in PathsCache  | 7 | 120 | 0 % | ***84 308 560*** | 18 % |  
_pathsCache in PathsProvider  | 6 | 120 | 0 % | 3 024 | 0 % |  
_provider  | 5 | 88 | 0 % | 3 072 | 0 % |  
mainModule in Package  | 5 | 200 | 0 % | 11 840 | 0 % |  
autocomplete-paths | 4 | 24 | 0 % | 6 312 | 0 % |  

That seems a bit excessive.

Here's a list of paths actually retained, along with the *count* of times they are found in _filePathsByDirectory:

```
/: 1
/GhcMod: 17
/GhcMod/Exe: 17
/NotCPP: 17
/bench: 17
/bench/data: 17
/bench/data/simple-cabal: 17
/core: 17
/core/Data: 17
/core/Data/Binary: 17
/core/GhcMod: 17
/core/GhcMod/Caching: 307
/core/GhcMod/Monad: 307
/core/GhcMod/Options: 307
/doc: 17
/doc/presentation: 17
/doc/presentation/auto: 17
/elisp: 17
/scripts: 17
/shared: 17
/shared/System: 17
/shared/System/Directory: 17
/shelltest: 17
/shelltest/browse: 17
/shelltest/browse/cabal: 17
/shelltest/browse/plain: 17
/shelltest/browse/sandbox: 17
/src: 17
/src/GhcMod: 17
/src/GhcMod/Exe: 17
/src/GhcMod/Exe/Options: 17
/test: 17
/test-elisp: 17
/test/data: 242
/test/data/annotations: 242
/test/data/broken-cabal: 242
/test/data/broken-cabal/.cabal-sandbox: 879
/test/data/broken-cabal/.cabal-sandbox/packages: 2510
/test/data/broken-cabal/.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d: 2510
/test/data/broken-cabal/.cabal-sandbox/x86_64-linux-ghc-7.10.3-packages.conf.d: 2510
/test/data/broken-cabal/.cabal-sandbox/x86_64-linux-ghc-8.0.1-packages.conf.d: 2510
/test/data/broken-cabal/.cabal-sandbox/x86_64-linux-ghc-8.0.2-packages.conf.d: 2502
/test/data/broken-sandbox: 242
/test/data/cabal-flags: 242
/test/data/cabal-preprocessors: 242
/test/data/cabal-project: 242
/test/data/cabal-project/.cabal-sandbox: 878
/test/data/cabal-project/.cabal-sandbox/i386-osx-ghc-7.6.3-packages.conf.d: 2262
/test/data/cabal-project/.cabal-sandbox/packages: 2262
/test/data/cabal-project/.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d: 2262
/test/data/cabal-project/.cabal-sandbox/x86_64-linux-ghc-7.10.3-packages.conf.d: 2262
/test/data/cabal-project/.cabal-sandbox/x86_64-linux-ghc-8.0.1-packages.conf.d: 2262
/test/data/cabal-project/.cabal-sandbox/x86_64-linux-ghc-8.0.2-packages.conf.d: 2254
/test/data/cabal-project/subdir1: 882
/test/data/cabal-project/subdir1/subdir2: 882
/test/data/case-split: 242
/test/data/check-missing-warnings: 242
/test/data/check-packageid: 242
/test/data/check-packageid/.cabal-sandbox: 638
/test/data/check-packageid/.cabal-sandbox/i386-osx-ghc-7.6.3-packages.conf.d: 799
/test/data/check-packageid/.cabal-sandbox/packages: 797
/test/data/check-packageid/.cabal-sandbox/x86_64-linux-ghc-8.0.2-packages.conf.d: 793
/test/data/check-test-subdir: 242
/test/data/check-test-subdir/src: 482
/test/data/check-test-subdir/src/Check: 482
/test/data/check-test-subdir/src/Check/Test: 482
/test/data/check-test-subdir/test: 482
/test/data/check-test-subdir/test/Bar: 482
/test/data/custom-cradle: 242
/test/data/custom-cradle/package-db-a: 482
/test/data/custom-cradle/package-db-b: 482
/test/data/custom-cradle/package-db-c: 482
/test/data/duplicate-pkgver: 242
/test/data/duplicate-pkgver/.cabal-sandbox: 639
/test/data/duplicate-pkgver/.cabal-sandbox/i386-osx-ghc-7.6.3-packages.conf.d: 797
/test/data/duplicate-pkgver/.cabal-sandbox/packages: 795
/test/data/duplicate-pkgver/.cabal-sandbox/x86_64-linux-ghc-8.0.2-packages.conf.d: 791
/test/data/file-mapping: 242
/test/data/file-mapping/lhs: 242
/test/data/file-mapping/preprocessor: 242
/test/data/foreign-export: 242
/test/data/ghc-mod-check: 242
/test/data/ghc-mod-check/lib: 482
/test/data/ghc-mod-check/lib/Data: 482
/test/data/hlint: 242
/test/data/home-module-graph: 242
/test/data/home-module-graph/cpp: 242
/test/data/home-module-graph/cycle: 242
/test/data/home-module-graph/errors: 242
/test/data/home-module-graph/indirect: 242
/test/data/home-module-graph/indirect-update: 242
/test/data/import-cycle: 242
/test/data/nice-qualification: 242
/test/data/non-exported: 242
/test/data/pattern-synonyms: 242
/test/data/quasi-quotes: 242
/test/data/stack-project: 242
/test/data/stack-project/app: 641
/test/data/stack-project/src: 641
/test/data/stack-project/test: 641
/test/data/target: 242
/test/data/template-haskell: 242
/test/manual: 242
/test/manual/not-interpreted-error: 242
```

(these stats were obtained by running the following equivalent code in console:
```js
Array.from(p.mainModule._provider._pathsCache._filePathsByDirectory.keys())
.map(a => a.path).reduce((acc,x) => { acc[x] = (acc[x] || 0) + 1; return acc }, {})
```
note it doesn't even touch map *values*)

I believe the problem is in using `Directory` objects as keys, which are not at all guaranteed to be the same if paths are the same (also, remember, objects are compared by-reference). Consider keying on string paths, or, alternatively, switching to `WeakMap`s where possible. Latter option at least won't make autocomplete-paths a single retainer, although it can lead to spontaneous cache invalidation.

**Comment by lierdakil** [comment] 2017-08-24 12:18
I believe the issue is introduced by https://github.com/atom-community/autocomplete-paths/commit/5c1c564703c696be30903978634b47a8eb508a52

**Comment by saschagehlich** [comment] 2017-08-24 12:28
There's definitely still a lot of memory optimizations that can be done, but I don't think that it's caused by using `Directory` instances as keys. In this case, we would see multiple occurrences of the same path in the list you posted.

I think one of the problems is the fact that I'm using strings as values. You can see that multiple keys are holding pretty much exactly the same file paths:

```
/test/data/stack-project/app: 641
/test/data/stack-project/src: 641
/test/data/stack-project/test: 641
```

We could reduce memory usage by using `File` objects instead, this way the arrays would point to the same object instead of holding copies of strings.

**Comment by lierdakil** [comment] 2017-08-24 12:33
For the love of... There *ARE* multiple occurrences. `/test/data/cabal-project/.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d` occurs  **2262** TIMES. This list doesn't even ***touch*** map values.

**Comment by lierdakil** [comment] 2017-08-24 12:34
`p.mainModule._provider._pathsCache._filePathsByDirectory.size = 52546`

**Comment by saschagehlich** [comment] 2017-08-24 12:34
Oh - I misread your code snippet. I thought it would print the amount of strings in the arrays (values). Sorry 'bout that.

Then you're absolutely right - will work on a fix

**Comment by saschagehlich** [comment] 2017-08-24 12:42
A fix has landed in 2.8.1 - thanks for reporting @lierdakil and sorry for the misunderstanding

**Closed by saschagehlich** 2017-08-24 12:42 UTC
Labels: bug

**Comment by lierdakil** [comment] 2017-08-24 12:45
Thanks. Sorry if I overreacted a bit. But I even explicitly noted that snipped doesn't touch map values in the OP...

**Comment by saschagehlich** [comment] 2017-08-24 12:46
Yeah I read that, but thought you meant you didn't look at the memory usage of the values, just at the amount of items 🙈
