### ISSUE TITLE
Atom freezes when editing a link inside a SCSS file

### ISSUE THREAD

**Issue by ConstantinChirila** [atom-community/autocomplete-paths#90] opened 2016-07-05 11:15 UTC
For example i got this in a SCSS file: 

`$fontURL: "https://fonts.googleapis.com/css?family=Source+Sans+Pro:600";`

If i tried to edit the link for example change the 600 at the end into 700... Atom completely freezes and becomes unresponsive.

**Comment by jelmerdemaat** [comment] 2016-07-05 12:18
I get the same freeze in an HTML file when trying to include an image.

When trying to edit any of these attributes:

```
<img src="//placehold.it/100x100&text=Logo" alt="Logo" class="...">
```

the complete editor freezes for ~22 seconds.

Screenshot of timeline recording: 

![img](http://i.imgur.com/BjmJ9r3.png)

Seems to definitely be this plugin.

**Comment by jelmerdemaat** [comment] 2016-07-05 12:19
Possibly duplicate of #83

**Comment by kaji2** [comment] 2016-07-12 05:06
I also have the same freeze while typing a URL blocks.
Maybe #38 is the duplicate but already closed.
I think this issue haven't fixed yet.

**Comment by ConstantinChirila** [comment] 2016-08-16 09:47
Nothing changed with recent atom updates. So it's definitly something wrong with the plugin.
I really miss it :(

**Comment by saschagehlich** [comment] 2017-08-11 14:59
2.0.0 Should fix this

**Closed by saschagehlich** 2017-08-11 14:59 UTC
