### ISSUE TITLE
doesn't works

### ISSUE THREAD

**Issue by rainjm** [atom-community/autocomplete-paths#156] opened 2017-09-08 07:54 UTC
### Description of the issue

1. **open atom or new windows**
2. open project
3. Observe ...

![wsbdssqlxj](https://user-images.githubusercontent.com/9592236/30201024-d6ef5952-94ab-11e7-8482-a3484cc2eb2e.gif)

![wydrly5xtv](https://user-images.githubusercontent.com/9592236/30201855-ce22a736-94ae-11e7-9e92-1ecc412faf17.gif)

Need to be disabled and then enabled to work

### Versions
1.19.7

### Additional Information
configuration: https://gist.github.com/rainjm/80ba9a29d07f114ed3cbb47aea172855

**Comment by saschagehlich** [comment] 2017-09-14 16:21
Duplicate of #146

**Closed by saschagehlich** 2017-09-14 16:21 UTC
