### ISSUE TITLE
Problem with */ patterns + comment blocks

### ISSUE THREAD

**Issue by drawcard** [atom-community/autocomplete-paths#62] opened 2015-07-14 06:47 UTC
When I type something like 

``` php
/* 
Comment block
*/
```

The autocomplete paths feature kicks in, thinking I'm typing a directory path:

``` php
/*
Comment block
*/blah-blah/...
```

I have to press ESC to ignore the dropdown. 

One possible solution is to have an option to ignore all paths outside of the project folder in the sidebar, or disable / refine the recognition of glob patterns?

**Comment by drawcard** [comment] 2015-07-16 00:12
As a workaround I've turned off the preference to make the Enter key accept the completion suggestion (in the `autocomplete-plus` module). I now just hit the Tab key to accept things in the dropdown list.

**Comment by akaRem** [comment] 2015-11-18 19:35
+1 for problem: annoying thing when coding js and bash in the same project.
-1 for ignoring all paths outside of the project 

There should be logic to behave differently for different languages like bash, js, c, ruby, etc.
For example, js does not have no valid cases when path is not enclosed in quotes, but in bash it's ok.

**Comment by kankaristo** [comment] 2016-06-23 09:34
This sounds like a duplicate of https://github.com/atom-community/autocomplete-paths/issues/55. The same thing happens with `//`-style comments and `http://` as well.

**Comment by saschagehlich** [comment] 2017-08-11 15:54
2.0.0 only triggers in specific cases, so this is fixed

**Closed by saschagehlich** 2017-08-11 15:54 UTC
