### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by briannhinton** [atom-community/autocomplete-paths#43] opened 2015-02-04 02:38 UTC
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
Object.activate (/Users/Brian/.atom/packages/autocomplete-paths/lib/autocomplete-paths.coffee:8:25)
```

**Comment by joefitzgerald** [comment] 2015-02-04 02:38
Please check the repo before opening issues. Duplicate of #42 & #41.

**Closed by joefitzgerald** 2015-02-04 02:38 UTC

**Comment by briannhinton** [comment] 2015-02-04 02:40
I apologize. I thought some intelligence existed in the app if an issue didn't exist. I'll verify before submitting next time. Way to be on the ball responding.

**Comment by joefitzgerald** [comment] 2015-02-04 02:41
No problem. I thought so too, but apparently it doesn't exist for deprecations - only for errors.
