### ISSUE TITLE
Suggestion appears upon first keystroke

### ISSUE THREAD

**Issue by johncormack** [atom-community/autocomplete-paths#103] opened 2016-12-20 09:40 UTC
Hello, even though i have set up autocomplete plus to trigger the suggestion at 3 keystrokes, when autocomplete path is enabled, it triggers are 1 keystroke.

how do i fix this?

Thank you

**Comment by leggsimon** [comment] 2016-12-20 10:02
Thanks for the issue, which version are you on? And could you provide any more details as I can't reproduce this.

**Comment by johncormack** [comment] 2016-12-20 10:08
Right now it prompted me to update and this issue is gone but i have other issues pertaining to the HTML and CSS auto complete packages. They trigger like paths did, on first keystroke. I'll ask them why it does this. Thanks for the immediate response.

**Comment by leggsimon** [comment] 2016-12-20 15:52
Thanks, closing as appears to be resolved.

**Closed by leggsimon** 2016-12-20 15:52 UTC
