### ISSUE TITLE
I haven't been able to use it since 1.19.0

### ISSUE THREAD

**Issue by linjialiang** [atom-community/autocomplete-paths#134] opened 2017-08-15 04:45 UTC
Now the plugin has been upgraded to 2.6.0 but I still can't use it, it's not working！
After installing the plug-in, I didn't configure it.
Does this plug-in installation require special configuration?

**Comment by linjialiang** [comment] 2017-08-15 04:47
在安装了插件之后，我没有进行配置。
这个插件安装需要特殊配置吗?

**Comment by saschagehlich** [comment] 2017-08-15 05:15
Please specify `it's not working`

**Comment by linjialiang** [comment] 2017-08-15 05:22
Atom did not give me any description of the error
The only problem is that the path cannot be filled！

**Comment by saschagehlich** [comment] 2017-08-15 05:24
What OS are you on? Could you show me an example of what's not working? `autocomplete-paths` only triggers when really needed.

**Comment by linjialiang** [comment] 2017-08-15 05:25
![default](https://user-images.githubusercontent.com/8848263/29303143-1a45a17c-81bd-11e7-84b9-5762c2da1d75.png)

**Comment by saschagehlich** [comment] 2017-08-15 05:26
Duplicate of #131

**Closed by saschagehlich** 2017-08-15 05:26 UTC

**Comment by linjialiang** [comment] 2017-08-15 05:36
@saschagehlich 
I'm sorry!
I don't know the location of this configuration file
